Unknown config field: [db.migrations]
Unknown config field: [db.migrations.enabled]
Unknown config field: [db.migrations.schema_paths]
Unknown config field: [db.network_restrictions]
Unknown config field: [db.network_restrictions.enabled]
Unknown config field: [db.network_restrictions.allowed_cidrs]
Unknown config field: [db.network_restrictions.allowed_cidrs_v6]
Unknown config field: [auth.rate_limit]
Unknown config field: [auth.rate_limit.email_sent]
Unknown config field: [auth.rate_limit.sms_sent]
Unknown config field: [auth.rate_limit.anonymous_users]
Unknown config field: [auth.rate_limit.token_refresh]
Unknown config field: [auth.rate_limit.sign_in_sign_ups]
Unknown config field: [auth.rate_limit.token_verifications]
Unknown config field: [auth.rate_limit.web3]
Unknown config field: [auth.web3.solana]
Unknown config field: [auth.web3.solana.enabled]
Unknown config field: [auth.third_party.clerk]
Unknown config field: [auth.third_party.clerk.enabled]
Unknown config field: [auth.oauth_server]
Unknown config field: [auth.oauth_server.enabled]
Unknown config field: [auth.oauth_server.authorization_url_path]
Unknown config field: [auth.oauth_server.allow_dynamic_registration]
Unknown config field: [edge_runtime.deno_version]
WARN: no seed files matched pattern: supabase/seed.sql
supabase start is not running.
Try rerunning the command with --debug to troubleshoot the error.
